# Generated by Django 5.0 on 2026-08-31 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(max_length=20)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('family_relation', models.CharField(max_length=10)),
                ('family_relation_name', models.CharField(max_length=10)),
                ('family_contact_number', models.CharField(max_length=20)),
                ('donation_status', models.CharField(choices=[('Pending', 'Pending'), ('Not Booked', 'Not Booked'), ('Booked', 'Booked'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=20)),
                ('upload_medical_doc', models.FileField(blank=True, null=True, upload_to='')),
                ('donated_before', models.BooleanField()),
                ('family_consent', models.BooleanField()),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation Requests',
                'verbose_name_plural': 'Donation Requests',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_status', models.CharField(choices=[('Pending', 'Pending'), ('Not Booked', 'Not Booked'), ('Booked', 'Booked'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=20)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donationrequests')),
            ],
            options={
                'verbose_name': 'Appointments',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
