# Generated by Django 5.0 on 2025-05-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='hospital',
            field=models.CharField(max_length=100),
        ),
    ]
